### ISSUE TITLE
White page on domain status page in admin pannel

### ISSUE THREAD

**Issue by majidshirazy** [SamanSystems/RedReseller-WHMCS#1]
After last  update of this module the domain status page on admin pannel is displayed as a white page.

**Comment by amiri27** [comment]
Salam...

Did you buy license of WHMCS? Do you have access to new module samples?

Regards,

**Comment by majidshirazy** [comment]
Hello, No I don't have WHMCS license.

**Comment by amiri27** [comment]
Problem closed due to incomplete information
